### ISSUE TITLE
SMS block – Error

### ISSUE THREAD

**Issue by theRod15** [dexbarrett/clockworksms#5]
I have an error in the communicate by SMS block.
It does not take the value of the mobile number, it literally takes the variable $ mobile

Send SMS
Array
(
[to] => $ mobile
[from] => Adoc365
[content] => Welcome Adoc365
)

Exception occured:  E_ERROR

If you can help, i'd be blessed :)

**Comment by dexbarrett** [comment]
Hi, I don't know if the format is messed up or what, but it seems you have a space between `$` and `mobile`. If that's the variable you're using, it must be `$mobile`.

If that's not the problem, can you provide more details about the code you're using?

**Comment by dexbarrett** [comment]
Closed due to inactivity
